version: "3.9"
services:
  dashboard:
    build: .
    container_name: dash_revendas
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DASH_AUTH_SECRET=${DASH_AUTH_SECRET}
    restart: unless-stopped
